---
title: Luyuan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Luyuan
markdown: kramdown
permalink: "/:year/:month/:day/:title"
url: https://luyuan.me

description: [Excelsior!]
theme: jekyll-theme-minimal
google_analytics: [UA-176263407-1]
